config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :panels do
    collection do
      get 'my'
    end
    member do
      get 'dashboard'
    end
    resources :widgets do
      collection do
        get 'widget_partial'
      end
      member do
        get 'dashboard'
        get 'reload_data'
        get 'switch_activation'
      end
    end
  end

  root 'panels#index'

end

app/models/panel.rb
class Panel < ActiveRecord::Base

  #FIXME make this test
  module Visibility
    PRIVATE = 1
    PUBLIC_TO_VIEW = 2
    PUBLIC_TO_EDIT = 3

    def self.all(current_user)
      options = [PUBLIC_TO_EDIT]
      options += [PRIVATE, PUBLIC_TO_VIEW] if current_user
      options
    end
  end

  
  validates :name , presence: true
  has_many :widgets, :dependent => :destroy

  validate :permitted_visibility
 
  scope :active, lambda { where(:active => true) }
  scope :inactive, lambda { where(:active => false) }

  scope :visible_to_me, -> user {
    conditions = []
    conditions.push("users.id = #{user.id}") unless user.nil?
    conditions.push("panels.visibility = #{Visibility::PUBLIC_TO_VIEW}")
    conditions.push("panels.visibility = #{Visibility::PUBLIC_TO_EDIT}")
    joins("LEFT JOIN panels_users ON panels.id = panels_users.panel_id LEFT JOIN users ON users.id = panels_users.user_id").
    where(conditions.join(" OR ")).order(:created_at)
  }

  self.per_page = 5

  #FIXME make this test
  has_and_belongs_to_many :users

  def permitted_visibility
    if self.users.empty? && self.visibility != Visibility::PUBLIC_TO_EDIT
      errors.add(:visibility, I18n.t(:visibity_not_allowed))
    end
  end

  def allow_edit?(user)
     could_edit = self.visibility == Visibility::PUBLIC_TO_EDIT
     self.users.include?(user) unless could_edit
     could_edit
  end

end

app/controllers/panels_controller.rb
class PanelsController < ApplicationController

  before_filter :allow_iframe
  before_action :set_panel, only: [:show, :edit, :update, :destroy, :dashboard]

  def index
    @panels = Panel.visible_to_me(current_user).send(params[:panel_state] || 'active').paginate(:page => params[:page])
  end

  def my
    @panels = Panel.send(params[:panel_state] || 'active').paginate(:page => params[:page])
    render :action => :index
  end

  def show
    redirect_to panel_widgets_path(@panel)
  end

  def dashboard
    page = params[:page].to_i
    page += 1
    page = 1 if page > Panel.find(params[:id]).widgets.active.count
    @widget = Panel.find(params[:id]).widgets.active.paginate(:per_page => 1, :page => page).first
    params[:page] = page
  end

  # GET /panels/new
  def new
    @panel = Panel.new
  end

  # GET /panels/1/edit
  def edit
  end

  # POST /panels
  # POST /panels.json
  def create
    @panel = Panel.new(panel_params)
#current_user.valid?
#raise current_user.errors.inspect
    @panel.users << current_user if current_user

    if @panel.save
      redirect_to panel_widgets_path(@panel), notice: t(:panel_successfully_created)
    else
      render :new 
    end
  end

  # PATCH/PUT /panels/1
  # PATCH/PUT /panels/1.json
  def update
    respond_to do |format|
      if @panel.update(panel_params)
        format.html { redirect_to @panel, notice: 'Panel was successfully updated.' }
        format.json { render :show, status: :ok, location: @panel }
      else
        format.html { render :edit }
        format.json { render json: @panel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /panels/1
  # DELETE /panels/1.json
  def destroy
    @panel.destroy
    respond_to do |format|
      format.html { redirect_to panels_url, notice: 'Panel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_panel
      @panel = Panel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def panel_params
      params.require(:panel).permit(:name, :active, :visibility)
    end

    def allow_iframe
      response.headers.delete 'X-Frame-Options'
    end
end

app/helpers/panels_helper.rb
module PanelsHelper
end

app/views/panels/_askbot_widget.html.erb
<div class='col-md-12 panel_<%=widget.class.name.underscore%>'>
  <%= render :partial =>  'panels/common_widget' if action_name == 'dashboard' %>
  <div class='box box-widget'>
    <h1><%= t(:askbot_title)%> </h1>
    <h2><%= t(:askbot_subtitle)%> </h2>
    <% widget.questions.map do |question| %>
      <div class='box-header with-border'>
        <div class="user-block">
          <img class="img-circle" src="<%= widget.user(question['author']['id'])['avatar'].gsub('http://oraculo.serpro','') %>" alt="User Image">
          <span class="username"><a href="#"><%= question['author']['username'] %></a></span>
        </div>
      </div>

      <div class="box-body">
        <%= question['summary'].html_safe %>
      </div>   
    <% end %>
    
  </div>
</div>

app/views/panels/_common_widget.html.erb
<script type='text/javascript'>
  clearInterval(myTimer);
  var myTimer = setInterval(function(){ 
  $.ajax({
    url: "<%= dashboard_panel_path(@panel, :format => :js) %>",
    data: { page: "<%= params[:page] %>" }
  })}, <%= @widget.speed%>);
</script>

app/views/panels/_deploy_widget.html.erb
<div class='<%=widget.class.name.underscore%>'>
  <h1><%= t(:deploy_title)%> </h1>

  
</div>

app/views/panels/_form.html.erb
<%= form_for(@panel, html: {class: 'form-horizontal'}) do |f| %>
  <div class="box-body">
    <% if @panel.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@panel.errors.count, "error") %> prohibited this panel from being saved:</h2>

        <ul>
        <% @panel.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label t(:name), class: 'col-sm-2 control-label' %>
      <div class='col-sm-10'>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label t(:select_visibility), class: 'col-sm-2 control-label' %>
      <div class='col-sm-10'>
        <%= f.select(:visibility, Panel::Visibility.all(current_user).collect {|v| [ visibility_name(v), v ] }, { include_blank: true, selected: Panel::Visibility::PUBLIC_TO_EDIT},{:class => 'form-control' }) %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <div class="checkbox">
          <%= f.label(:active, f.check_box(:active) + t(:active)) %>
        </div>
      </div>
    </div>

  </div>
  <div class="box-footer">
    <%= link_to t(:cancel), panels_path, :class=>"btn btn-default" %>
    <%= f.submit (action_name == 'edit' ? t(:update_panel) : t(:new_panel)), :class => 'btn btn-primary' %>
  </div>

<% end %>

app/views/panels/_gitlab_widget.html.erb
<% @filter ||= {} %>
<div class='<%=widget.class.name.underscore%>'>
  <h1><%= t(:gitlab_title)%> </h1>
  <h2><%= t(:gitlab_subtitle)%> </h2>
  <ul>
    <h3><%= t(:gitlab_projects)%></h3>
    <% widget.activated_projects.map do |project| %>
      <li><%= project[:id].to_s + ': ' + project[:host] + '/' + project[:path_with_namespace] %></li>
    <% end %>
  </ul>
  <ul>
    <h3><%= t(:gitlab_filters)%></h3>
    <h4><%= t(:labels)%></h4>
    <% widget.labels.map do |label| %>
      <% if @filter.present? && @filter[:labels].include?(label)%>
        <li><%= link_to label, panel_widget_path(@panel, widget, :labels => (@filter[:labels] - [label]).join(',')), :class => 'selected' %></li>
      <% else %>
        <li><%= link_to label, panel_widget_path(@panel, widget, :labels => ((@filter[:labels] || []) + [label]).join(',')) %></li>
      <% end %>
    <% end %>
  </ul>
  <ul>
    <h3>
      <%= t(:gitlab_issues)%>
      <%= link_to t(:gitlab_reload_issues), reload_data_panel_widget_path(@panel, widget) %>
    </h3>
    <% widget.issues_by_filter(@filter).map do |issue| %>
      <li><%= gitlab_issue_url(widget, issue) %></li>
    <% end %>
  </ul>
</div>

app/views/panels/_jenkins_widget.html.erb
<div class='build-monitor dashboard industrial <%=widget.class.name.underscore%>'>
  <%= render :partial =>  'panels/common_widget' if action_name == 'dashboard' %>
  <main class="main">
    <h1><%= t(:jenkins_title)%> </h1>
    <h2><%= t(:jenkins_subtitle, widget_uri: widget.class.base_uri)%> </h2>
  
    <ul id="widgets" class="columns-3" style="">
      <% widget.jobs.map do |job| %>
        <li class="<%= JenkinsWidget.job_status(job['color']) %> basic project widget">
          <div class="progress" style="width: 30%; display: none;"><span >30%</span></div>
          <header>
            <h2><a title="<%= job['name'] %>" href="<%= job['url'] %>" ><%= job['name'] %></a></h2>
            <ul class="details" style="<%= (job['color'] == 'blue') ? 'display: none;' : ''   %>">
              <li><%= job['lastHealthReport']['description']  %></li>
            </ul>
          </header>
          <div class="slots">
            <div class="build-number slot slot-1" name="1">
              <a class="build-name ng-scope" title="Details of DE5CT » NoosferoFrontend-IC, build #20" href="<%= job['lastBuild']['url'] %>" > <span ><%= job['lastBuild']['number']%></span></a>
            </div>
            <div class="build-time slot slot-2" name="2">
              <div >
                <div class="build-time">
                  <span class="estimated ng-binding" title="Last execution"><%= time_ago_in_words(job['lastCompletedBuild']['datetime']) %></span>
                </div>
              </div>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  
  </main>

</div>

app/views/panels/_panel.html.erb
<li id="panel-<%= panel.id %>" class='panel'>
  <span><%= link_to panel.name, panel %></span>
  <%= t(:options_for_panel) %>
  <span><%= link_to t(:dashboard), dashboard_panel_path(panel) %></span>
  <span><%= link_to 'Widgets', panel_widgets_path(panel) %></span>
  <span><%= link_to t(:edit), edit_panel_path(panel) %></span>
  <span><%= link_to t(:remove), panel, method: :delete, data: { confirm: t(:are_you_sure) } %></span>
</li>

app/views/panels/_sonar_smile_widget.html.erb
<div class='panel_<%=widget.class.name.underscore%>'>
  <%= render :partial =>  'panels/common_widget' if action_name == 'dashboard' %>
  <h1><%= t(:sonar_smile_title)%> </h1>
  <h2><%= t(:sonar_smile_subtitle)%> </h2>

<% widget.systems_coverage.map do |system, coverage| %>
<!--  <%= coverage%> -->
  <div class="face">
    <div class="container">
      <div class="<%= SonarSmileWidget.feeling(coverage) %>">
        <%= SonarSmileWidget.face(coverage)%>
      </div>
    </div><!-- .container -->
    <div class='name'>
      <a><%= truncate(widget.pretty_name(system), :length => 20)%></a> 
    </div>
  </div><!-- .container -->
<% end %>
<br style='clear: both;'/>
</div>

app/views/panels/_sonar_widget.html.erb
<div class='<%=widget.class.name.underscore%>'>
  <%= render :partial =>  'panels/common_widget' if action_name == 'dashboard' %>
  <h1><%= t(:sonar_title)%> </h1>
  <h2><%= t(:sonar_subtitle, widget_uri: widget.class.base_uri)%> </h2>
  <% widget.systems_coverage.map do |system, coverage| %>
    <div class='system-info'>
      <div class="progress">
        <div class="progress-bar" role="progressbar" aria-valuenow="<%= coverage %>" aria-valuemin="0" aria-valuemax="100" style="width: <%=coverage%>%;">
          <div class='name'> <%= widget.pretty_name(system) %> </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/panels/_table.html.erb
<div class="table-green">

<table id="ledgers_<%=params[:tab]%>">
  <thead>
  <tr>
    <th></th>
    <th>ID</th>
    <th>Data</th>
    <th>Valor</th>
    <th>Descrição</th>
    <th>Tag list</th>
    <th>Detalhamento</th>
    <th>Tipo de Lançamento</th>
  </tr>
  </thead>

  <tfoot>
  <tr>
    <th></th>
    <th>ID</th>
    <th>Data</th>
    <th>Valor</th>
    <th>Descrição</th>
    <th>Tag list</th>
    <th>Detalhamento</th>
    <th>Tipo de Lançamento</th>
  </tr>
  </tfoot>

<tbody>
<% for ledger in @ledgers %>
  <%= render :partial => 'table_line', :locals => {:ledger => ledger} %>
<% end %>
</tbody>
</table>
</div>

<script type="text/javascript">

// Colorbox
$('.remote-form').colorbox();

/* Formatting function for row details - modify as you need */
function format ( d ) {
    // `d` is the original data object for the row
    return '<table cellpadding="6" cellspacing="0" border="0" style="padding-left:50px;">'+
        '<tr>'+
            '<td>Detalhamento:</td>'+
            '<td>'+d[6]+'</td>'+
        '</tr>'+
    '</table>';
}

  $(document).ready(function() {
    var table = $("#ledgers_<%=params[:tab]%>").DataTable({
        "order": [[ 2, "asc" ]],
//        "dom": '<"toolbar">lfrtip',
        "language": {
            "emptyTable":     "Nenhum dado disponível na tabela",
            "lengthMenu": "Mostrar _MENU_ registros por página",
            "zeroRecords": "Nenhum - sinto muito",
            "info": "Mostrar página _PAGE_ of _PAGES_",
            "infoEmpty": "Nenhum registro disponível",
            "infoFiltered": "(filtrar de _MAX_ total de registros)",
            "search": "Buscar:",
            "previous": "Anterior",
            "loadingRecords": "Carregando...",
	    "processing":     "Processando...",
            "next": "Próximo",
            "paginate": {
              "first":      "Primeiro",
              "last":       "Último",
              "next":       "Próximo",
              "previous":   "Anterior"
             },
             "aria": {
               "sortAscending":  ": ativar para ordenar colunas crescentemente",
               "sortDescending": ": ativar para ordenar colunas decrescentemente"
             }
        },
        "lengthMenu": [[-1,10, 25, 50], ['Todos',10, 25, 50]],
        "columnDefs": [
            { "visible": false, "targets": 6 },
            { "visible": false, "targets": 7 },
//            { "searchable": false, "targets": 4 }
        ],
        "search": {
          "regex": true
        },
        "drawCallback": function ( settings ) {
            var api = this.api();
            var rows = api.rows( {page:'current'} ).nodes();
            var last=null;
 
            api.column(7, {page:'current'} ).data().each( function ( group, i ) {
                if ( last !== group ) {
                    $(rows).eq( i ).before(
                        '<tr class="group"><td colspan="8">'+group+'</td></tr>'
                    );
 
                    last = group;
                }
            } );
          },
//       "ajax": "http://localhost:3000/static.json",
//      "columns": [
//            {
//                "class":          'details-control',
//                "orderable":      false,
//                "data":           null,
//                "defaultContent": ''
//            },
//            { "data": "date" },
//            { "data": "value" },
//            { "data": "description" },
//            { "data": "tag_list" },
//            { "data": "detail" }
//        ],
       "footerCallback": function ( row, data, start, end, display ) {
          var api = this.api();
          // Remove the formatting to get integer data for summation
          var intVal = function ( i ) {
              return typeof i === 'string' ?  i.replace(/[\$,]/g, '')*1 : typeof i === 'number' ? i : 0;
          };
          // Total over all pages
          var total = api
              .column( 3 )
              .data()
              .reduce( function (a, b) {
                  return intVal(a) + intVal(b);
              } );
 
          // Total over this page
          var pageTotal = api
              .column( 3, { page: 'current'} )
              .data()
              .reduce( function (a, b) {
                  return intVal(a) + intVal(b);
              } );
           // Update footer
          $( api.column( 3 ).footer() ).html(
              'R$ '+ pageTotal +' de R$ '+ total +''
          );
       },
//    "drawCallback": function ( settings ) {
//            var api = this.api();
//            var rows = api.rows( {page:'current'} ).nodes();
//            var last=null;
// 
//            api.column(3, {page:'current'} ).data().each( function ( group, i ) {
//                if ( last !== group ) {
//                    $(rows).eq( i ).before(
//                        '<tr class="group"><td colspan="5">'+group+'</td></tr>'
//                    );
// 
//                    last = group;
//                }
//            } );
//          }
//
    });


//    $("div.toolbar").html('<b>Lançamentos do Ikê.</b>');

  // Add event listener for opening and closing details
    $('#ledgers_<%=params[:tab]%> tbody').on('click', 'td.details-control', function () {
        var tr = $(this).closest('tr');
        var row = table.row( tr );
 
        if ( row.child.isShown() ) {
            // This row is already open - close it
            row.child.hide();
            tr.removeClass('shown');
        }
        else {
            // Open this row
            row.child( format(row.data()) ).show();
            tr.addClass('shown');
        }
    } );

  // Order by the grouping
    $('#ledgers_<%=params[:tab]%> tbody').on( 'click', 'tr.group', function () {
        var currentOrder = table.order()[0];
        if ( currentOrder[0] === 7 && currentOrder[1] === 'asc' ) {
            table.order( [ 7, 'desc' ] ).draw();
        }
        else {
            table.order( [ 7, 'asc' ] ).draw();
        }
    } );

  } );
</script>

app/views/panels/_widget.html.erb
<iframe src="<%= widget.url %>"id="iframe_<%= widget.id%>" width='100%' height='700px'></iframe>  

app/views/panels/dashboard.html.erb
<% breadcrumb :panel, @panel %>


<div id='dashboard-display' class='dashboard-display'>
  <%= render :partial => partial_for_widget(@widget), :locals => {:widget => @widget} %>
</div>

app/views/panels/edit.html.erb
<% breadcrumb :edit_panel %>

<h1> <%= t(:edit_panel) %> </h1>

<div class="box box-primary">
  <%= render 'form' %>
</div>

app/views/panels/show.html.erb
<% breadcrumb :panel, @panel %>

<div class='carousel'>

  <% @widgets.map do |widget| %>
    <div class="item <%= widget == @widgets[0] ? 'active' : ''%>">
    <%= widget.name %>
    </div>
  <% end %>
</div>