config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :panels do
    collection do
      get 'my'
    end
    member do
      get 'dashboard'
    end
    resources :widgets do
      collection do
        get 'widget_partial'
      end
      member do
        get 'dashboard'
        get 'reload_data'
        get 'switch_activation'
      end
    end
  end

  root 'panels#index'

end

app/models/widget.rb
class Widget < ActiveRecord::Base

  @@widget_config = {}

  validates_presence_of :name

  #FIXME make this test
  scope :active, lambda { where(:active => true) }

  #FIXME validates this presence
  belongs_to :panel

  has_settings :data

  after_initialize do
    self.load_config
  end

  def self.permit
    [:name, :speed]
  end

  def self.widget_types
    [SonarWidget, SonarSmileWidget, AskbotWidget, UrlWidget, JenkinsWidget]
  end

  def reload_data!
    #Subscribe this method in child class
  end


  #FIXME make this test
  def switch_activation!
    value = self.active ?  false : true
    self.update!(:active => value)
  end

  #FIXME make this test
  def self.load_config
    file_path = File.expand_path("#{Rails.root}/config/widgets/#{self.name.underscore}.yml", __FILE__)
    return nil unless File.exists?(file_path)
    @@widget_config ||= {}
    @@widget_config[self.name.underscore] = YAML.load(ERB.new(File.read(file_path)).result)
  end

  def load_config
    self.class.load_config
  end

  #FIXME make this test
  def self.widget_config
    @@widget_config[self.name.underscore]
  end

  #FIXME make this test
  def widget_config
    self.class.widget_config#[self.class.name.underscore]
  end
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  before_action :set_panel
  before_action :set_widget, only: [:show, :edit, :update, :destroy, :reload_data, :switch_activation, :dashboard]
  before_action :set_filter

  # GET /widgets
  # GET /widgets.json
  def index
    @widgets = @panel.widgets.paginate(:page => params[:page])
  end

  # GET /widgets/1
  # GET /widgets/1.json
  def show
  end

  def dashboard
  end

  # GET /widgets/new
  def new
    @widget = load_widget
  end

  # GET /widgets/1/edit
  def edit
  end

  # POST /widgets
  # POST /widgets.json
  def create
    @widget = load_widget#(widget_params)
    @widget.panel = @panel

    respond_to do |format|
      if @widget.save
        format.html { redirect_to panel_widget_path(@panel, @widget), notice: 'Widget was successfully created.' }
        format.json { render :show, status: :created, location: @widget }
      else
        format.html { render :new }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if @widget.update(widget_params)
      redirect_to panel_widgets_path(@panel), notice: t(:widget_successfully_updated)
    else
      render :edit
    end
  end

  # DELETE /widgets/1
  # DELETE /widgets/1.json
  def destroy
    @widget.destroy
    respond_to do |format|
      format.html { redirect_to panel_widgets_url(@panel), notice: 'Widget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def widget_partial
    @widget = load_widget
    respond_to do |format|
      format.js
    end
  end

  def reload_data
    @widget.reload_data!
    respond_to do |format|
      format.html { redirect_to panel_widget_path(@panel, @widget), notice: 'Widget was successfully reloaded.' }
      format.json { render :show, status: :ok, location: @widget }
    end
  end

  def switch_activation
    @widget.switch_activation!
    respond_to do |format|
      format.html { redirect_to panel_widgets_path(@panel), notice: 'Widget was successfully updated' }
#      format.json { render :show, status: :ok, location: @widget }
    end
  end
  private

    # Use callbacks to share common setup or constraints between actions.
    def set_panel
      @panel = Panel.find(params[:panel_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_widget
      @widget = @panel.widgets.find(params[:id])
    end
    def set_filter
      @filter ||= {}
      @filter[:labels] = (params[:labels] || '').split(',')
    end

    def load_widget
      klass = Widget.descendants.detect{|w| w.name == params[:type]}
      @widget = (klass || UrlWidget).new(widget_params(klass))
      @widget
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def widget_params(klass = nil)
      return {} if params[:widget].blank?
      params.require(:widget).permit((@widget.nil? ? klass : @widget.class).permit)
    end
end

app/helpers/widgets_helper.rb
module WidgetsHelper
  
  def gitlab_issue_url(widget, issue)
    project = widget.project_by_issue(issue)
    url = project[:host] + '/' + project[:path_with_namespace] + "/issues/#{issue[:iid]}"
    label = GitlabWidget.server_name(project[:host]) + ': ' + project[:name] + ' - ' + issue[:iid].to_s + ': ' + issue[:title].to_s
    link_to(label, url, :target => "_blank")
  end

  def switch_activave_label(active)
    active ? t(:deactivate)  : t(:activate)
  end
 
end

app/views/widgets/_deploy_widget_form.html.erb
<div class="field">
  <%= label_tag 'widget[system]', t(:system) %>
  <%= text_field_tag 'widget[system]', @widget.system, size: 60 %>
</div>
<div class="field">
  <%= label_tag 'widget[identifier]', t(:identifier) %>
  <%= text_field_tag 'widget[identifier]', @widget.identifier, size: 60 %>
</div>
<div class="field">
  <%= label_tag 'widget[who]', t(:who) %>
  <%= text_field_tag 'widget[who]', @widget.who, size: 60 %>
</div>

app/views/widgets/_form.html.erb
<div class="box-body">
<% if @widget.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@widget.errors.count, "error") %> prohibited this widget from being saved:</h2>

    <ul>
    <% @widget.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group">
  <%= label_tag 'widget[name]', t(:name), :class => 'col-sm-2 control-label' %>
  <div class='col-sm-10'>
    <%= text_field_tag 'widget[name]', @widget.name %>
  </div>
</div>

<span id='partial_for_widget'>
<%= render :partial => partial_for_widget(@widget) + '_form' %>
</span>

  <div class="form-group">
    <%= label_tag 'widget[speed]', t(:speed),  class: 'col-sm-2 control-label' %>
    <div class='col-sm-10'>
    <%= text_field_tag 'widget[speed]', @widget.speed %>
    </div>
  </div>

<% if @widget.new_record? %>
  <div class="form-group">
    <%= label_tag 'type', t(:type),  class: 'col-sm-2 control-label' %>
    <div class='col-sm-10'>
      <%= select_tag 'type', options_for_select(Widget.widget_types.map{|a| [a.model_name.human, a.to_s]}, @widget.type), {:id => 'widget_type', :class => 'form-control' } %>
    </div>
  </div>
<% end %>
</div>
<div class="box-footer">
  <%= link_to t(:cancel), panel_widgets_path(@panel), :class=>"btn btn-default" %>
  <%= f.submit (action_name == 'edit' ? t(:update_widget) : t(:new_widget)), :class => 'btn btn-primary' %>
</div>

app/views/widgets/_gitlab_widget_form.html.erb
<div class="field">
  <%= label_tag 'widget[uri]', t(:uri) %>
  <%=  GitlabWidget.base_uri %>
</div>

<div class="field">
<% @widget.projects.map do |project| %>
    <%= check_box 'widget', 'activated_projects', {:checked => project[:active], :multiple => true}, project[:id]%>
    <%= label_tag 'widget[activated_projects]', project[:path_with_namespace] %>
<% end %>
</div>
 

app/views/widgets/_jenkins_widget_form.html.erb
<div class="form-group">
  <%= label_tag 'widget[uri]', t(:uri), class: 'col-sm-2 control-label' %>
  <div class='col-sm-10' >
    <%=  @widget.class.base_uri %>
  </div>
</div>
<div class="form-group">
  <%= label_tag 'widget[job_path]', t(:jenkins_job_path), :class => 'col-sm-2 control-label' %>
  <div class='col-sm-10' >
    <%= text_field_tag 'widget[job_path]', @widget.job_path %>
  </div>
</div>
<div class="form-group">
  <%= label_tag 'widget[include_systems_re]', t(:jenkins_include_systems_re), :class => 'col-sm-2 control-label' %>
  <div class='col-sm-10' >
    <%= text_field_tag 'widget[include_systems_re]', @widget.include_systems_re %>
  </div>
</div>

app/views/widgets/_sonar_smile_widget_form.html.erb
_sonar_widget_form.html.erb

app/views/widgets/_sonar_widget_form.html.erb
<div class="form-group">
  <%= label_tag 'widget[uri]', t(:uri), class: 'col-sm-2 control-label' %>
  <div class='col-sm-10' >
    <%=  @widget.class.base_uri %>
  </div>
</div>

<div class="form-group">
  <%= label_tag 'widget[include_systems_re]', t(:sonar_include_systems_re), :class => 'col-sm-2 control-label' %>
  <div class='col-sm-10' >
    <%= text_field_tag 'widget[include_systems_re]', @widget.include_systems_re %>
  </div>
</div>

app/views/widgets/_table_widget_form.html.erb
<div class="field">
  <%= label_tag 'widget[uri]', t(:table) %>
</div>

app/views/widgets/_url_widget_form.html.erb
<div class="form-group">
  <%= label_tag 'widget[url]', t(:url),  class: 'col-sm-2 control-label' %>
  <div class='col-sm-10'>
    <%= text_field_tag 'widget[url]', @widget.url, size: 60 %>
  </div>
</div>

app/views/widgets/_widget.html.erb
<li id="widget-<%= widget.id %>">
  <span><%= link_to widget_fullname(widget), panel_widget_path(panel, widget) %></td>
  <span><%= link_to t(:dashboard), dashboard_panel_widget_path(panel, widget) %></td>
  <span><%= link_to switch_activave_label(widget.active), switch_activation_panel_widget_path(panel,widget) %></span>
  <span><%= link_to t(:edit), edit_panel_widget_path(panel,widget) %></span>
  <span><%= link_to t(:remove), panel_widget_path(panel, widget), method: :delete, data: { confirm: t(:are_you_sure) } %></span>
</li>

app/views/widgets/dashboard.html.erb
<div class='dashboard-display'>
  <%= render :partial => 'panels/'+partial_for_widget(@widget), :locals => {:widget => @widget} %>
</div>

app/views/widgets/edit.html.erb
<% breadcrumb :edit_widget, @panel, @widget %>

<h1> <%= t(:edit_widget) %> </h1>

<div class="box box-primary <%= @widget.class.name.underscore %>">
<%= form_for([@panel, @widget], :url => panel_widget_path(@panel, @widget.id), :method => :put,  :html => {class: 'form-horizontal'}) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
<% end %>
</div>

app/views/widgets/index.html.erb
<% breadcrumb :list_widgets, @panel%>

<h1>
  <%= t('list_widgets', panel_name: @panel.name) %>
  <%= link_to t(:action_new), new_panel_widget_path(@panel) %>
</h1>

<ul id='list-of-widgets'>
  <%= render :partial => 'widget', :locals => {:panel => @panel}, :collection => @widgets %>
</ul>

<%= will_paginate @widgets %>

app/views/widgets/new.html.erb
<% breadcrumb :new_widget, @panel %>

<h1> <%= t(:new_widget) %> </h1>


<div class="box box-primary <%= @widget.class.name.underscore %>">
  <%= form_for([@panel, @widget], :url => panel_widgets_path(@panel, @widget), :html => {class: 'form-horizontal'}) do |f| %>
      <%= render :partial => 'form', :locals => {:f => f} %>
  <% end %>
</div>

app/views/widgets/show.html.erb
<% breadcrumb :show_widget, @panel, @widget %>

<%= render :partial => 'panels/'+partial_for_widget(@widget), :locals => {:widget => @widget} %>