config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :panels do
    collection do
      get 'my'
    end
    member do
      get 'dashboard'
    end
    resources :widgets do
      collection do
        get 'widget_partial'
      end
      member do
        get 'dashboard'
        get 'reload_data'
        get 'switch_activation'
      end
    end
  end

  root 'panels#index'

end

app/views/layouts/_admin_lte_2_header.html.erb
<!-- Main Header -->
<header class="main-header">

  <!-- Logo -->
  <a href="/" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>D</b>B</span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>Dash</b>Board</span>
  </a>

  <!-- Header Navbar -->
  <nav class="navbar navbar-static-top" role="navigation">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    <!-- Navbar Right Menu -->
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <!-- User Account Menu -->
        <% if user_signed_in? %>
        <li class="dropdown user user-menu">
          <!-- Menu Toggle Button -->
          <a href="#" class="dropdown-toggle" data-toggle="collapse" data-target="#user-detail">
            <!-- The user image in the navbar-->
            <img src="<%= current_user.avatar.url(:thumb) %>" class="user-image" alt="User Image"/>
            <!-- hidden-xs hides the username on small devices so only the image appears. -->
            <span class="hidden-xs"><%= current_user.login %></span>
          </a>
          <ul class="dropdown-menu collapse" id='user-detail'>
            <!-- The user image in the menu -->
            <li class="user-header">
              <img src="<%= current_user.avatar.url(:medium) %>" class="img-circle" alt="User Image" />
              <p>
                <%= current_user.login %>
                <small><%= t(:member_since, time: time_ago_in_words(current_user.created_at)) %></small>
              </p>
            </li>
            <!-- Menu Footer-->
            <li class="user-footer">
<!--
              <div class="pull-left">
                <a href="#" class="btn btn-default btn-flat">Profile</a>
              </div>
-->
              <div class="pull-right">
                <%= link_to t(:sign_out), destroy_user_session_path, method: :delete, class: 'btn btn-default btn-flat' %>
              </div>
            </li>
          </ul>
        </li>
        <% else %>
        <li class="dropdown user user-menu">
          <!-- Menu Toggle Button -->
          <%= link_to t(:sign_in), new_user_session_path, class: 'btn btn-default' %>
        </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_admin_lte_2_sidebar.html.erb
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">

  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">

    <!-- Sidebar user panel (optional) -->
    <% if user_signed_in? %>
    <div class="user-panel">
      <div class="pull-left image">
        <img src="<%= current_user.avatar.url(:medium) %>" class="img-circle" alt="User Image" />
      </div>
      <div class="pull-left info">
        <p><%= current_user.login %></p>
      </div>
    </div>
    <% end %>

    <!-- search form (Optional) -->
    <!--
    <form action="#" method="get" class="sidebar-form">
      <div class="input-group">
        <input type="text" name="q" class="form-control" placeholder="Search..."/>
        <span class="input-group-btn">
          <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
        </span>
      </div>
    </form>
    -->
    <!-- /.search form -->

    <!-- Sidebar Menu -->
    <ul class="sidebar-menu">
      <li class="header"><%= t(:menu) %></li>
        <!-- Optionally, you can add icons to the links -->
      <li class="active"><%= link_to "<i class='fa fa-link'></i><span>#{t(:public_panels)}</span>".html_safe, panels_path %></li>
      <% if user_signed_in? %>
      <li class="treeview">
        <%= link_to "<i class='fa fa-dashboard'></i><span>#{t(:my_panels)}</span><i class='fa fa-angle-left pull-right'></i>".html_safe, my_panels_path %>
        <ul class="treeview-menu">
          <% current_user.panels.map do |panel| %>
            <li>
              <%= link_to "<i class='fa fa-circle-o'></i> #{panel.name}".html_safe, panel_path(panel) %>
            </li>
          <% end %>
        </ul>
      </li>
      <% end %>
    </ul><!-- /.sidebar-menu -->
  </section>
  <!-- /.sidebar -->
</aside>

app/views/layouts/admin_lte_2.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Dashboard</title>
  <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
  <link href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->

  <%= csrf_meta_tags %>
</head>

<body class="skin-blue sidebar-mini fixed <%= params[:controller].parameterize %> <%= action_name %>">
  <div class="wrapper">

    <%= render partial: 'layouts/admin_lte_2_header' %>

    <%= render partial: 'layouts/admin_lte_2_sidebar' %>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">

      <!-- Main content -->
      <section class="content">
        <% if notice %>
          <div class="alert alert-success alert-dismissable">
            <i class="fa fa-check"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <b><%= notice %></b>
          </div>
        <% end %>

        <% if alert %>
          <div class="alert alert-danger alert-dismissable">
            <i class="fa fa-ban"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <b><%= alert %></b>
          </div>
        <% end %>
        <%= breadcrumbs pretext: t(:you_are_here), :style => :bootstrap %>
        <%= yield %>
      </section><!-- /.content -->
    </div><!-- /.content-wrapper -->

    <!-- Main Footer -->
    <footer class="main-footer">
      <!-- To the right -->
      <div class="pull-right hidden-xs">
        Anything you want
      </div>
      <!-- Default to the left -->
      <strong>Copyleft &copy; 2016 <a href="#">Serpro</a>.</strong> All rights reserved.
    </footer>


  </div><!-- ./wrapper -->

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/layouts/admin_lte_2_login.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>AdminLTE 2 | Log in</title>
  <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>
<body class="login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="/"><b>Admin</b>LTE</a>
  </div><!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Sign in to start your session</p>
    <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
      <div class="form-group has-feedback">
        <%= f.text_field :email, class: 'form-control', autofocus: true %>
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>

      <div class="form-group has-feedback">
        <%= f.password_field :password, class: 'form-control', autocomplete: 'off' %>
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <div class="row">
        <div class="col-xs-8">
          <div class="checkbox icheck">
            <label>
              <input type="checkbox"> Lembrar
            </label>
          </div>
        </div><!-- /.col -->
        <div class="col-xs-4">
          <%= f.submit 'Log in', class: 'btn btn-primary btn-block btn-flat' %>

        </div><!-- /.col -->
      </div>

    <% end %>
  </div><!-- /.login-box-body -->
</div><!-- /.login-box -->

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dashboard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="wrapper" class="<%= params[:screen].nil? ? '' : 'toggled'%>">
  
    <!-- Sidebar -->
    <div id="sidebar-wrapper">
      <ul class="sidebar-nav">
        <li class="sidebar-brand">
          <%= link_to 	t(:init), panels_path %>
        </li>
<!--
        <li>
            <a href="#">Dashboard</a>
        </li>
        <li>
            <a href="#">Shortcuts</a>
        </li>
        <li>
            <a href="#">Overview</a>
        </li>
        <li>
            <a href="#">Events</a>
        </li>
        <li>
            <a href="#">About</a>
        </li>
        <li>
            <a href="#">Services</a>
        </li>
        <li>
            <a href="#">Contact</a>
        </li>
-->
      </ul>
    </div>
    <!-- /#sidebar-wrapper -->
  
    <!-- Page Content -->
    <div id="page-content-wrapper">
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-12">
            <% if params[:screen].nil? %>
             <a href="#menu-toggle" class="btn btn-default" id="menu-toggle"><%= t(:toggle_menu)%></a>
            <% end %>
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
    <!-- /#page-content-wrapper -->
  
  </div>
    <!-- /#wrapper -->

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>


</body>
</html>